### ISSUE TITLE
Feature Request: Extended Configuration Support

### ISSUE THREAD

**Issue by khaos-codi** [iksnae/book-tools#2]
## Extended Configuration Support

As part of the migration from the bespoke build system in `book-template` to the standardized `book-tools` solution, we need to enhance the configuration support in `book-tools` to match or exceed the capabilities of the current system.

### Current State in book-template

The `book-template` repository currently supports a rich configuration format in `book.yaml` that includes:

```yaml
# PDF settings
pdf:
  paper_size: "letter"
  margin_top: "1in"
  margin_right: "1in"
  margin_bottom: "1in"
  margin_left: "1in"
  font_size: "11pt"
  line_height: "1.5"
  template: "templates/pdf/default.latex"

# EPUB settings
epub:
  cover_image: "book/images/cover.png"
  css: "templates/epub/style.css"
  toc_depth: 3

# HTML settings
html:
  template: "templates/html/default.html"
  css: "templates/html/style.css"
  toc: true
  toc_depth: 3
  section_divs: true
  self_contained: true
```

### Required Changes

We need to extend the `book-tools` configuration schema to support format-specific settings:

1. **PDF Settings**
   - Paper size
   - Margins
   - Font size
   - Line height
   - Custom template

2. **EPUB Settings**
   - Cover image path
   - Custom CSS
   - Table of contents depth

3. **HTML Settings**
   - Custom template
   - Custom CSS
   - Table of contents options
   - Section divisions
   - Self-contained output

### Implementation Approach

1. Update the configuration loading logic in `src/utils.js` to include format-specific settings.
2. Add default values for all format-specific settings.
3. Apply these settings when generating the output files.
4. Create a configuration adapter to convert between the formats.

### Testing

Tests should be added to verify that:
1. The configuration format is properly loaded and validated.
2. Default values are applied when settings are missing.
3. Custom settings are properly applied to the output.

This enhancement will ensure that users migrating from `book-template` can maintain the same level of customization they currently have.
