### ISSUE TITLE
Feature Request: GitHub Actions Integration

### ISSUE THREAD

**Issue by khaos-codi** [iksnae/book-tools#4]
## GitHub Actions Integration

As part of the migration from the bespoke build system in `book-template` to the standardized `book-tools` solution, we need to add explicit support for GitHub Actions to ensure seamless CI/CD integration.

### Current State in book-template

The `book-template` repository uses a GitHub Actions workflow for automated builds:

```yaml
name: Build Book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: iksnae/book-builder:latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build book
      run: ./build.sh --all-languages
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: book-outputs
        path: build/**/*
```

### Required Features

We need to implement GitHub Actions integration in `book-tools`:

1. **GitHub Actions CLI Command**
   - Add a `github-action` command to the CLI
   - Support special flags for CI/CD environments
   - Handle artifact generation for GitHub Actions

2. **Workflow Templates**
   - Create example workflow files for different scenarios
   - Update CI environment detection
   - Handle authentication for advanced features

3. **Release Integration**
   - Add support for creating GitHub releases
   - Handle version tagging
   - Support release notes generation

### Implementation Approach

1. **Extend CLI**
   - Add a `github-action` command to `src/cli.js`
   - Implement special error handling for CI environments
   - Add logging optimized for CI output

2. **Create Templates**
   - Create example workflow files in a new `templates/github-actions` directory
   - Document all available options
   - Provide examples for different book configurations

3. **Document Integration**
   - Update README.md with GitHub Actions integration instructions
   - Create a dedicated GitHub Actions guide
   - Document all available CI/CD options

### Testing

Tests should be added to verify that:
1. The CLI behaves correctly in CI environments
2. GitHub Actions specific features work as expected
3. Error reporting is clear in CI logs
4. Artifacts are generated correctly

This enhancement will ensure that users migrating from `book-template` can maintain their existing CI/CD workflows while leveraging the standardized `book-tools` package.
